name: Go Build and Test

on:
  push: # Triggers on pushes to any branch
  pull_request: # Triggers on pull requests to any branch

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }} (Go ${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.22'] # Specify a recent Go version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go tests
        run: go test ./...

      - name: Build Go project
        run: go build ./...
